### Crear un nuevo apunte
POST http://localhost:3000/api/apuntes
Content-Type: application/json  

{
    "titulo_apunte": "Ades",
    "descripcion_apunte": "Resumen Final Practica",
    "numero_alumno": 1,
    "cod_materia": 1,
    "archivo_apunte": "data:application/pdf;base64,...",  
    "archivo_caratula": "data:image/jpeg;base64,..."      
}


### Obtener todos los apuntes
GET http://localhost:3000/api/apuntes

### Obtener apuntes por materia ordenados por calificacion
GET http://localhost:3000/api/apuntes/materias/2

### Obtener los apuntes publicados de un alumno
GET http://localhost:3000/api/apuntes/alumnos/1



### Obtener un apunte por ID
GET http://localhost:3000/api/apuntes/8

### Actualizar un apunte por ID
PUT http://localhost:3000/api/apuntes/8
Content-Type: application/json

{
  "titulo_apunte": "Resumen del parcial 2",
  "descripcion_mod_apunte": "Actualización del título del apunte"
}


### Eliminar un apunte por ID
DELETE http://localhost:3000/api/apuntes/3




### AHORA HAGO CRUD DE PRECIO

### Crear un nuevo precio
POST http://localhost:3000/api/precios
Content-Type: application/json

{
  "id_apunte": 4,
  "monto_precio": 3500
}

### Obtener el último precio de un apunte por su ID
GET http://localhost:3000/api/precios/7

### AHORA HAGO CRUD COMPRA

### Crear una nueva compra
POST http://localhost:3000/api/compras
Content-Type: application/json

{
    "numero_alumno": 1,
    "id_apunte": 8
}

### Actualizar Calificación
PATCH http://localhost:3000/api/compras/1/5
Content-Type: application/json

{
    "calificacion_apunte_comprador":8
}


### Obtener todas las compras de alumno
GET http://localhost:3000/api/compras/1

### Obtener una unica compra
GET http://localhost:3000/api/compras/1/5



### Dar de alta un alumno
POST http://localhost:3000/api/alumnos
Content-Type: application/json
{
    "numero_usuario": 1,
    "nombre_apellido_alumno": "Agustin Garcia",
    "email_usuario": "agustin@gmail.com",
    "nombre_usuario": "AgustinGarcia2307",
    "telefono_usuario": "3425474935",
    "contraseña_usuario": "admin",
    "legajo_usuario": "12345"
}
